CON_PORT: RiCBoard
FILE_NAME: caja-komodo
Battery/name: battery_monitor
Battery/pubHz: 10
Battery/voltageDividerRatio: 5.98
closeLoop0/publishHz: 50
closeLoop0/name: left_motor
closeLoop0/LPFAlpha: 0.7
closeLoop0/LPFHz: 50
closeLoop0/driverAddress: 999
closeLoop0/channel: 1
closeLoop0/port: 1
closeLoop0/PIDHz: 1000
closeLoop0/kP: 10.0
closeLoop0/kI: 25.0
closeLoop0/kD: 0
closeLoop0/limit: 1.0
closeLoop0/maxSpeed: 16.0
closeLoop0/cpr: 2048
closeLoop0/timeout: 1000
closeLoop0/motorType: 1
closeLoop0/encoderType: 1
closeLoop0/direction: 1
closeLoop0/directionE: -1
closeLoop1/publishHz: 50
closeLoop1/name: right_motor
closeLoop1/LPFAlpha: 0.7
closeLoop1/LPFHz: 50
closeLoop1/driverAddress: 999
closeLoop1/channel: 0
closeLoop1/port: 2
closeLoop1/PIDHz: 1000
closeLoop1/kP: 10.0
closeLoop1/kI: 25.0
closeLoop1/kD: 0
closeLoop1/limit: 1.0
closeLoop1/maxSpeed: 16.0
closeLoop1/cpr: 2048
closeLoop1/timeout: 1000
closeLoop1/motorType: 1
closeLoop1/encoderType: 1
closeLoop1/direction: 1
closeLoop1/directionE: 1
Diff/publishHz: 10
Diff/name: diff_driver
Diff/rWheel: 0.1311
Diff/width: 0.396
Diff/baseLink: base_link
Diff/odom: odom_link
Diff/slip: 0.85
Diff/maxAng: 16.0
Diff/maxLin: 16.0
Diff/motorL: 0
Diff/motorR: 1
IMU_INIT: 0
GPS_INIT: 0
PPM_INIT: 0
BAT_INIT: 1
DIFF_INIT: 1
DIFF_INIT_OP: 0
DIFF_CLOSE_FOUR: 0
closeLoopNum: 2
switchNum: 0
servoNum: 0
relayNum: 0
URFNum: 0
openLoopNum: 0
