obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.50, -0.50], [-0.50, 0.50], [0.50, 0.50], [0.50,-0.50]]
inflation_radius: 0.50
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: Laser_link, data_type: LaserScan, topic: /komodo_1/scan, marking: true, clearing: true}
